apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
  labels:
    app: supermario-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario-deployment
  template:
    metadata:
      labels:
        app: supermario-deployment
    spec:
      containers:
      - name: supermario
        image: emerson4linux/8729-mario:0.5 
        ports:
        - containerPort: 8080
