name: Variáveis Global no Workflow

on:
  workflow_dispatch:
env:
  Ambiente: 'Desenvolvimento'
  Versao: '1.0.0'
  SAUDACAO: 'Olá, mundo!'


jobs:
  vars_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir Variáveis de Ambiente
        run: |
          echo "Ambiente: $Ambiente"
          echo "Versão: $Versao"
          echo "$SAUDACAO"

  teste_vars:
    runs-on: ubuntu-latest
    needs: vars_workflow
    steps:
      - name: Teste de Variáveis
        run: |
          echo "Ambiente: $Ambiente"
          echo "Versão: $Versao"
          echo "$SAUDACAO"


  teste_vars_novamente:
    runs-on: ubuntu-latest
    needs: vars_workflow
    steps:
      - name: Teste de Variáveis
        run: |
          echo "Ambiente: $Ambiente"
          echo "Versão: $Versao"
          echo "$SAUDACAO"