name: Variáveis no Workflow

on:
  workflow_dispatch:


jobs:
  vars_workflow:
    runs-on: ubuntu-latest
    env:
      Ambiente: "Desenvolvimento"
      Versao: "1.0.0"
      SAUDACAO: "Seja bem-vindo ao workflow de variáveis!"
    steps:
      - name: Exibir Variáveis de Ambiente
        run: |
          echo "Ambiente: $Ambiente"
          echo "Versão: $Versao"
          echo "$SAUDACAO"

  teste_vars:
    runs-on: ubuntu-latest
    needs: vars_workflow
    steps:
      - name: Teste de Variáveis
        run: |
          echo "Ambiente: $Ambiente"
          echo "Versão: $Versao"
          echo "$SAUDACAO"
