name: Merge to Main Workflow

on:
  push:
    branches: [ "dev" ]


jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Execução pos merge 
        run: |
          echo "Executando tarefas pós-merge no branch main"
